#+HUGO_BASE_DIR: /home/hugh/HMLW
#+HUGO_SECTION: post

#+hugo_weight: auto
#+hugo_auto_set_lastmod: t

#+author: admin

* Website :@website:
This folder holds all posts relating to the running of this website.
** DONE Pixelfed and photo journalling :hugo:photos:org:emacs:tools:
:PROPERTIES:
:EXPORT_HUGO_FRONT_MATTER_FORMAT: yaml
:EXPORT_FILE_NAME: index
:EXPORT_DATE: 2020-04-28
:EXPORT_HUGO_BUNDLE: pixelfed-and-photo-journalling
:EXPORT_HUGO_CUSTOM_FRONT_MATTER: :summary Writing a post on Pixelfed using Emacs orgmode. :image\n"placement: 2\nfocal point: \"\"  \npreview_only: false"
:END:

This short blog post serves two purposes: to mention a bit more about Pixelfed and the beginning of my photo journal, and a test of the =ox-hugo= export functionality in Emacs orgmode.

[[https://pixelfed.org][Pixelfed]] is a federated, open-source alternative to Instagram. I have setup a [[https://pixelfed.de/hmlwilliams][profile]] using the https://pixel.de, but hopefully I will be able to work out self-hosting an instance shortly. The functionality of the site is exceptional, and it works well on mobile too. Another excellent feature is that one can embed iframes of posts and profiles, I have my profile embedded on the home page, and there is an example post of some hot cross buns that I baked for Easter Sunday down below. Overall I am very pleased with it, and hope to continue my photo journalling efforts.

#+begin_export html
<p align="center">
<iframe src="https://pixelfed.de/p/hmlwilliams/160445294222381056/embed?caption=false&likes=false&layout=compact" class="pixelfed__embed" style="max-width: 100%; border: 0" width="400" allowfullscreen="allowfullscreen"></iframe><script async defer src="https://pixelfed.de/embed.js"></script>
</p>
#+end_export

Finally, just a quick note, I have been writing this post using the =ox-hugo= package for Emacs, which allows me to write posts as subheadings in an org file and then directly export them as markdown files for Hugo. Getting it setup didn't take too long, and would have been quicker if I had read things more carefully. Again, I am happy with the way it works and will continue to use it as and when I can.
